#!/bin/bash
# Batch 6 Corrections - Generated by Claude Code Audit
# Generated: 2025-11-16 13:17:50
# Total corrections: 5

API_URL="http://localhost:8001"

echo "Applying 5 corrections for Batch 6..."
echo ""

echo "[1/5] Correcting Sanctuary2_20251101_104338_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/0307f96c-2a91-4286-8010-96c90f39e946/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 6"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[2/5] Correcting Sanctuary2_20251101_174253_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/f183d605-7f8b-4d21-8cd5-c8004edf8e68/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 6"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[3/5] Correcting Hayfield_20251020_064531_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/e00690e1-2410-4b3a-8d9f-7a2150949598/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 6"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[4/5] Correcting Sanctuary2_20251109_064211_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/0e8a9c6b-0c3d-40fa-ac42-ce6c07afcf66/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 6"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[5/5] Correcting Sanctuary2_20251102_171248_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/925c431f-cf0f-4d1a-8a19-245d066ab6f1/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 6"}' \
  && echo "  [OK]" || echo "  [FAILED]"


echo ""
echo "Batch 6 corrections complete!"
echo "Applied 5 corrections"
