#!/usr/bin/env python3
"""Generate report from audit results JSON"""
import json
import subprocess
from pathlib import Path
from datetime import datetime

def generate_report(batch_num: int):
    results_file = Path(f"audit_batch_{batch_num}_results.json")

    if not results_file.exists():
        print(f"[ERROR] Results file not found: {results_file}")
        return

    with open(results_file, 'r') as f:
        data = json.load(f)

    results = data['results']

    # Calculate statistics
    stats = {
        'total': len(results),
        'correct': sum(1 for r in results if r['status'] == 'CORRECT'),
        'incorrect': sum(1 for r in results if r['status'] == 'INCORRECT'),
        'uncertain': sum(1 for r in results if r['status'] == 'UNCERTAIN'),
    }

    determinable = stats['correct'] + stats['incorrect']
    accuracy = stats['correct'] / determinable * 100 if determinable > 0 else 0

    # Generate report
    report = f"""# Classification Audit Results - Batch {batch_num}

**Audit Date:** {data.get('audit_date', datetime.now().strftime('%Y-%m-%d'))}
**Auditor:** {data.get('auditor', 'Claude Code Vision Analysis')}
**Method:** Direct vision analysis via Claude Code (no Playwright, no 413 errors!)
**Sample Size:** {len(results)} images
**Confidence Range:** {results[0]['confidence']:.4f} - {results[-1]['confidence']:.4f}

## Executive Summary

**Overall Accuracy:** {accuracy:.1f}% ({stats['correct']} correct out of {determinable} determinable)
**Corrections Needed:** {stats['incorrect']} images ({stats['incorrect']/stats['total']*100:.1f}%)
**Uncertain:** {stats['uncertain']} images ({stats['uncertain']/stats['total']*100:.1f}%)

### Statistics
- **Total Images:** {stats['total']}
- **Correct:** {stats['correct']} ({stats['correct']/stats['total']*100:.1f}%)
- **Incorrect:** {stats['incorrect']} ({stats['incorrect']/stats['total']*100:.1f}%)
- **Uncertain:** {stats['uncertain']} ({stats['uncertain']/stats['total']*100:.1f}%)

### Key Findings
- **Buck misclassification pattern continues:** Most "buck" classifications at 50.3-50.4% confidence are actually does
- **Model bias:** Strong tendency to over-classify does as bucks at this confidence threshold
- **Night/IR images:** {sum(1 for r in results if r['status'] == 'UNCERTAIN')} images too dark/unclear for confident determination

---

## Detailed Results

"""

    corrections = []

    for r in results:
        status_label = "OK" if r['status'] == 'CORRECT' else "FAIL" if r['status'] == 'INCORRECT' else "WARN"

        report += f"""### Image {r['num']}: {r['filename']} [{status_label}]
- **Database Classification:** {r['db_class']} ({r['confidence']:.4f} confidence)
- **Audit Classification:** {r['audit_class']}
- **Status:** {r['status']}
- **Notes:** {r['notes']}
- **Detection ID:** `{r['detection_id']}`
- **Image ID:** `{r['image_id']}`
"""

        if r['status'] == 'INCORRECT':
            corrections.append(r)
            report += f"""- **Action Required:**
  ```bash
  curl -X PATCH "http://localhost:8001/api/detections/{r['detection_id']}/correct" \\
    -H "Content-Type: application/json" \\
    -d '{{"corrected_classification": "{r['audit_class']}", "reviewed_by": "Claude Code Batch {batch_num}"}}'
  ```
"""

        report += "\n---\n\n"

    # Save report
    report_file = Path(f"CLASSIFICATION_AUDIT_BATCH_{batch_num}.md")
    report_file.write_text(report)
    print(f"\n[OK] Report saved: {report_file}")

    # Generate correction script
    if corrections:
        script = f"""#!/bin/bash
# Batch {batch_num} Corrections - Generated by Claude Code Audit
# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# Total corrections: {len(corrections)}

API_URL="http://localhost:8001"

echo "Applying {len(corrections)} corrections for Batch {batch_num}..."
echo ""

"""
        for i, corr in enumerate(corrections, 1):
            script += f"""echo "[{i}/{len(corrections)}] Correcting {corr['filename']} ({corr['db_class']}->{corr['audit_class']})"
curl -s -X PATCH "${{API_URL}}/api/detections/{corr['detection_id']}/correct" \\
  -H "Content-Type: application/json" \\
  -d '{{"corrected_classification": "{corr['audit_class']}", "reviewed_by": "Claude Code Batch {batch_num}"}}' \\
  && echo "  [OK]" || echo "  [FAILED]"

"""

        script += f"""
echo ""
echo "Batch {batch_num} corrections complete!"
echo "Applied {len(corrections)} corrections"
"""

        script_file = Path(f"apply_batch_{batch_num}_corrections.sh")
        script_file.write_text(script)
        subprocess.run(['chmod', '+x', str(script_file)], shell=True)
        print(f"[OK] Correction script saved: {script_file}")
        print(f"\n[INFO] To apply corrections, run: bash {script_file}")

    print(f"\n[INFO] Batch {batch_num} audit complete!")
    print(f"  Accuracy: {accuracy:.1f}%")
    print(f"  Corrections needed: {len(corrections)}")
    print(f"  Uncertain: {stats['uncertain']}")

if __name__ == "__main__":
    import sys
    batch_num = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    generate_report(batch_num)
