#!/bin/bash
# Batch 8 Corrections - Generated by Claude Code Audit
# Generated: 2025-11-16 13:41:09
# Total corrections: 8

API_URL="http://localhost:8001"

echo "Applying 8 corrections for Batch 8..."
echo ""

echo "[1/8] Correcting 270_JASON_00987.jpg (doe->cattle)"
curl -s -X PATCH "${API_URL}/api/detections/5729c2e3-1638-491e-b237-20929689c40b/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "cattle", "reviewed_by": "Claude Code Batch 8"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[2/8] Correcting Sanctuary2_20251102_170527_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/68915282-d5a5-4da7-9ec2-e7c345535172/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 8"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[3/8] Correcting Sanctuary2_20251101_155809_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/ba64c7ef-da4f-4a64-8fef-5fb5f601d4fc/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 8"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[4/8] Correcting Sanctuary2_20251102_172737_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/890e6d39-5b47-49f2-81c8-6e395b709968/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 8"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[5/8] Correcting Sanctuary2_20251104_175600_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/6df5240f-f99a-4334-9bba-93dc866872e5/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 8"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[6/8] Correcting HAYFIELD_11181.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/2db2b7fa-f221-470e-808b-a4e96f9ca353/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 8"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[7/8] Correcting Sanctuary2_20251106_093639_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/34ffcea7-e475-4f23-ba09-1f0b24fdad23/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 8"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[8/8] Correcting Sanctuary2_20251101_152609_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/b39d8efd-68d0-44c2-b328-bb047211b322/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 8"}' \
  && echo "  [OK]" || echo "  [FAILED]"


echo ""
echo "Batch 8 corrections complete!"
echo "Applied 8 corrections"
