#!/bin/bash
# Batch 4 Corrections - Generated by Claude Code Audit
# Generated: 2025-11-16 15:19:28
# Total corrections: 11

API_URL="http://localhost:8001"

echo "Applying 11 corrections for Batch 4..."
echo ""

echo "[1/11] Correcting Sanctuary2_20251108_173213_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/6d909440-4502-4b3b-8c44-aa7cd408ceb1/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[2/11] Correcting Sanctuary2_20251101_110905_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/26e25389-65c7-4193-b1d1-32e719db8b1c/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[3/11] Correcting Hayfield_20250918_075928_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/33d86a56-b928-4aa6-a28d-be4d13ed7282/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[4/11] Correcting Sanctuary2_20251101_165327_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/49430f45-c915-4f12-ab41-3c3e9f2b67fa/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[5/11] Correcting Sanctuary2_20251106_090419_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/851d4bfc-af53-42cf-9424-8c1355c1a424/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[6/11] Correcting Sanctuary2_20251102_170510_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/7f54eb1c-b555-4fdf-9a70-b34dcf5ea24b/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[7/11] Correcting Jason1_20251009_202123_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/4ff4d91b-a79d-4081-acc0-cee02c994f73/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[8/11] Correcting Sanctuary2_20251101_102202_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/45f790a8-024e-45df-8e48-c70359186549/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[9/11] Correcting Sanctuary2_20251102_173105_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/e231603b-1d12-4504-8b76-fc0edd372b54/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[10/11] Correcting Hayfield_20251014_172146_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/c607e4db-3068-4608-a74d-9181c4228865/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[11/11] Correcting Hayfield_20250914_080518_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/4c9cb3a9-1f50-458e-aa15-cfa038d574da/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 4"}' \
  && echo "  [OK]" || echo "  [FAILED]"


echo ""
echo "Batch 4 corrections complete!"
echo "Applied 11 corrections"
