#!/bin/bash
# Batch 5 Corrections - Generated by Claude Code Audit
# Generated: 2025-11-16 13:04:41
# Total corrections: 7

API_URL="http://localhost:8001"

echo "Applying 7 corrections for Batch 5..."
echo ""

echo "[1/7] Correcting Sanctuary2_20251105_162347_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/1fdd8444-0f4f-4fc2-bc1d-062fa5d9bab2/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 5"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[2/7] Correcting Hayfield_20250915_085120_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/9c8db883-c966-468a-a949-dd41ae326930/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 5"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[3/7] Correcting Sanctuary2_20251031_185455_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/a82ffed4-4c1c-45c3-9e93-6e9c54e0c14a/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 5"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[4/7] Correcting Sanctuary2_20251101_174834_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/0a217184-8ecc-40ba-aef2-9fa4983cabde/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 5"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[5/7] Correcting Sanctuary2_20251104_160627_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/7b03c491-b681-4d94-aa71-1d40ad971e56/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 5"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[6/7] Correcting Sanctuary2_20251102_173314_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/f2330acd-fa16-4a33-acea-015b0f273f1a/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 5"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[7/7] Correcting Sanctuary2_20251104_174343_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/3397cece-aff1-4fa7-904d-6a05082a86bc/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 5"}' \
  && echo "  [OK]" || echo "  [FAILED]"


echo ""
echo "Batch 5 corrections complete!"
echo "Applied 7 corrections"
