#!/bin/bash
# Batch 10 Corrections - Generated by Claude Code Audit
# Generated: 2025-11-16 15:17:26
# Total corrections: 2

API_URL="http://localhost:8001"

echo "Applying 2 corrections for Batch 10..."
echo ""

echo "[1/2] Correcting Sanctuary2_20251102_104549_001.jpg (doe->buck)"
curl -s -X PATCH "${API_URL}/api/detections/fd78669a-2fbe-4c56-8828-cc7bb40f71fb/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "buck", "reviewed_by": "Claude Code Batch 10"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[2/2] Correcting HAYFIELD_02001.jpg (doe->buck)"
curl -s -X PATCH "${API_URL}/api/detections/37f40fa6-6962-46d8-8f99-9a6805dbe876/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "buck", "reviewed_by": "Claude Code Batch 10"}' \
  && echo "  [OK]" || echo "  [FAILED]"


echo ""
echo "Batch 10 corrections complete!"
echo "Applied 2 corrections"
