#!/bin/bash
# Batch 7 Corrections - Generated by Claude Code Audit
# Generated: 2025-11-16 13:21:44
# Total corrections: 8

API_URL="http://localhost:8001"

echo "Applying 8 corrections for Batch 7..."
echo ""

echo "[1/8] Correcting Sanctuary2_20251102_172509_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/50c19df5-42d2-48e3-966a-4c8444a70dec/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 7"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[2/8] Correcting HAYFIELD_09436.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/5848b938-1b1a-4c71-b070-c0268f7d1684/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 7"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[3/8] Correcting Hayfield_20251108_032521_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/b05be066-38de-40d1-8500-367db2f5e1b4/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 7"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[4/8] Correcting Sanctuary2_20251106_124944_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/49edd3a8-0d3d-4f2e-a584-517f4b15126c/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 7"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[5/8] Correcting CAMPHOUSE_00666.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/9014ded2-bb12-481c-9c6a-50d9f885363f/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 7"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[6/8] Correcting Sanctuary2_20251105_164037_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/eeccfbe6-e02d-4c8b-97fa-8092d81efec6/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 7"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[7/8] Correcting Sanctuary2_20251109_072747_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/a921fb16-e9ae-4d8e-87a2-7f177823c33d/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 7"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[8/8] Correcting Sanctuary2_20251102_162757_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/f0d70dc7-14e7-4917-800b-f67dacc4b92e/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 7"}' \
  && echo "  [OK]" || echo "  [FAILED]"


echo ""
echo "Batch 7 corrections complete!"
echo "Applied 8 corrections"
