#!/bin/bash
# Batch 9 Corrections - Generated by Claude Code Audit
# Generated: 2025-11-16 16:25:42
# Total corrections: 6

API_URL="http://localhost:8001"

echo "Applying 6 corrections for Batch 9..."
echo ""

echo "[1/6] Correcting Sanctuary2_20251109_072016_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/9ddc4cc1-be51-4906-88a0-f8a947d074f7/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 9"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[2/6] Correcting Sanctuary2_20251101_175303_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/b56cf15e-4d75-4ff7-8617-54f29ad24a8f/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 9"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[3/6] Correcting Sanctuary2_20251102_172617_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/d1a4d239-20a5-4176-b1f4-48e4ab70ea69/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 9"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[4/6] Correcting Sanctuary2_20251101_154731_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/f29d099d-5f17-4d9c-9823-4f6ab0f49f1a/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 9"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[5/6] Correcting Sanctuary2_20251102_163847_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/0ccae99d-3aa0-4682-be23-a760e674850a/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 9"}' \
  && echo "  [OK]" || echo "  [FAILED]"

echo "[6/6] Correcting Sanctuary2_20251102_172917_001.jpg (buck->doe)"
curl -s -X PATCH "${API_URL}/api/detections/2fec528b-20eb-4d4b-acac-7353a2d56141/correct" \
  -H "Content-Type: application/json" \
  -d '{"corrected_classification": "doe", "reviewed_by": "Claude Code Batch 9"}' \
  && echo "  [OK]" || echo "  [FAILED]"


echo ""
echo "Batch 9 corrections complete!"
echo "Applied 6 corrections"
